[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/messagelib/',
    '@layerzerolabs/protocol/=lib/LayerZero-v2/protocol/',
    '@layerzerolabs/messagelib/=lib/LayerZero-v2/messagelib/',
    '@layerzerolabs/oapp/=lib/LayerZero-v2/oapp/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@layerzerolabs/lz-evm-v1-0.7/=node_modules/@layerzerolabs/lz-evm-v1-0.7/',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
]